version: '3.8'

services:
  rolemanager.webservice:
    container_name: rolemanager.webservice
    image: ${DOCKER_REGISTRY-}rolemanagerwebservice
    build:
      context: .
      dockerfile: RoleService/RoleManager.WebService/Dockerfile
    environment:
      - DAPR_HTTP_PORT=3500
    networks:
      - rolemanager
    command: ["dotnet", "ef", "database update"]
    depends_on:
      - mssql
      - redis
    ports:
      - "3500"

  rolemanager-dapr:
    image: "daprio/daprd"
    command: [
      "./daprd",
     "-app-id", "rolemanager.webservice",
     "-app-port", "80",
     "-components-path", "/components",
     "-config", "/config/config.yaml",
     "-log-level", "debug"
     ]
    volumes:
      - "./RoleService/dapr/components/:/components"
      - "./RoleService/dapr/config/:/config"  
    network_mode: "service:rolemanager.webservice"


  redis:
    container_name: rolemanager-redis
    image: "redis:6"
    ports:
      - "6380:6379"
    networks:
      - rolemanager

  mssql:
    container_name: rolemanager-mssql
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyPass@word
      - MSSQL_PID=Express
    ports:
      - "1439:1433"
    networks:
      - rolemanager

networks:
  rolemanager: