version: '3.4'

services:
  rolemanager.webservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  roleconfig.webservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
